name: Værvarsel Monitor

on:
  schedule:
    # Kjører hver dag kl 09:00 UTC (10:00/11:00 norsk tid)
    - cron: '0 9 * * *'
  
  # Tillat manuell kjøring fra Actions-fanen
  workflow_dispatch:

jobs:
  weather-check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    
    - name: Run weather monitor
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        USER_EMAIL: ${{ secrets.USER_EMAIL }}
        THRESHOLD_PRECIPITATION_HOURLY: ${{ vars.THRESHOLD_PRECIPITATION_HOURLY || '5.0' }}
        THRESHOLD_PRECIPITATION_DAILY: ${{ vars.THRESHOLD_PRECIPITATION_DAILY || '20.0' }}
        THRESHOLD_TEMPERATURE_SWING: ${{ vars.THRESHOLD_TEMPERATURE_SWING || '10.0' }}
      run: |
        python weather_monitor.py
